set(SRC_FILES
    App.cpp
    game/GameSession.cpp
    utils/AtlasLoader.cpp
    utils/FpsOverlay.cpp
    enemy/Enemy.cpp
    enemy/EnemyManager.cpp
    map/GridMap.cpp
    map/Tile.cpp
    tower/Tower.cpp
    tower/TowerManager.cpp
    tower/AmmoTower.cpp
    tower/AroundSkillTower.cpp
)

set(INCLUDE_FILES
    App.hpp
    game/GameSession.hpp
    game/LevelConfig.hpp
    utils/AtlasLoader.hpp
    utils/FpsOverlay.hpp
    enemy/Enemy.hpp
    enemy/EnemyTypeConfig.hpp
    enemy/EnemyManager.hpp
    map/GridMap.hpp
    map/Tile.hpp
    tower/Tower.hpp
    tower/TowerManager.hpp
    tower/AmmoTower.hpp
    tower/AroundSkillTower.hpp
)

set(TEST_FILES
)
